// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhbwwjuerkxxqvsskeog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oYnd3anVlcmt4eHF2c3NrZW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTM0MjksImV4cCI6MjA2OTYyOTQyOX0.249vcGiKhmfvleAb4cwOp1UBJNk2ldYdnLhMvHC4bm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});